# Generated by Django 3.1.8 on 2021-04-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
