# Generated by Django 3.1.8 on 2021-04-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20210419_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='', verbose_name='Эмблема стихии'),
        ),
    ]
