# Generated by Django 3.1.8 on 2021-04-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_pokemonelementtype_strong_against'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Эмблема стихии'),
        ),
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='pokemon_entities.PokemonElementType'),
        ),
    ]
